### PR TITLE
Resolve optimiser free day conflicts

### LINKED ISSUE #4072: Optimiser free day conflict does not work as intended
### Describe the bug
The free days conflict does not work as intended for modules with two or more lessons such as CS1231S lectures.

### To Reproduce

Image

Image

1. Add CS1231S to the timetable
2. Navigate to optimiser and choose CS1231S Lecture to be a lesson you want to attend live
3. Choose "Thursday" and notice there is no free days conflict
4. Now also choose "Friday" and notice now there is a free day conflict

### Expected behavior

When "Thursday" or "Friday" alone is chosen it must show free days conflict.

### PR DESCRIPTION
**Pull request by samthambad**
## Context

Closes #4072 [Optimiser free day conflict does not work as intended](https://github.com/nusmodifications/nusmods/issues/4072)

## Implementation
The free days are now checked with all the groups/classNo, to find in-person class groups which are not possible to attend due to missing >=1 lesson. of that group, useful for lectures especially.

## Other Information

- The conflicting days just show up as the chosen free days, the error has been reworded to 'cannot be assigned due to your free days' for it to work with this use case.

### CODE REVIEW

File: website/src/views/optimiser/OptimiserContent.tsx [hunk 1]
```diff
@@ -130,9 +162,40 @@ const OptimiserContent: React.FC = () => {
...
     });
-
+    // check if all groups are not possible to attend, then it's a conflict, then day of conflict is the days of one of the groups
+    // go thorugh each module-lessonType combination, and within that,
+    // go through each group and within that check if any of the selected free days are in them, if so, that group is invalid
+    lessonGroupsData.forEach((groupMap, uniqueKey) => {
+      let validGroups = 0;
+      groupMap.forEach((days, _groupName) => {
+        if (
+          recordings.includes(uniqueKey.split('-').join(' ')) || // if it is a recorded lesson, dont trigger a conflict
```
Comment (leslieyip02) [inline website/src/views/optimiser/OptimiserContent.tsx]: Could we change `recordings` to be a set of `uniqueKey` instead of `displayText`? Then we can just do `recordings.includes(uniqueKey)` and we wouldn't need to convert here.

File: package-lock.json
Comment (leslieyip02) [inline package-lock.json:1]: Can you remove this `package-lock.json` file?

File: website/src/views/optimiser/OptimiserForm.tsx [hunk 2]
```diff
@@ -185,8 +185,13 @@ const OptimiserForm: React.FC<OptimiserFormProps> = ({
           </div>
           {freeDayConflicts.map((conflict, index) => (
             <div key={index} className={styles.conflictItem}>
-              • <strong>{conflict.displayText}</strong> happens on:{' '}
-              {conflict.conflictingDays.join(', ')}
+              • <strong>{conflict.displayText}</strong> cannot be assigned due to your free days:{' '}
+              {conflict.conflictingDays
+                .sort((a, b) => {
+                  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
```
Comment (leslieyip02) [inline website/src/views/optimiser/OptimiserForm.tsx]: You can import `WorkingDays` from `types/modules`.

**Review by leslieyip02 — CHANGES_REQUESTED** [review]
Thanks for the PR! It seems to solve the issue, but I have left a few comments.

Also, I edited your PR description to [link this PR to the issue directly](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue).

**Comment by thejus03** [comment]
Thanks @samthambad. I believe the conflict is working well!

However the free days shown might be **incorrect**.
For instance, this is the previous version. Notice the free days that are shown.
image

Now notice the free days shown in this. If I am not wrong, it just shows all days I selected.
image

**Comment by samthambad** [comment]
Hi @leslieyip02, I've made the changes based on your comments. Thank you for the feedback !
