### PR TITLE
Several Bug Fixes to Optimiser

### LINKED ISSUE #4069: Optimiser should accept classes that start after 1900
### Describe the bug

The optimiser has a  "Latest class option" that goes up to 1900. However, it is possible for a class to start at 2100 (e.g. [YSS3257](https://nusmods.com/courses/YSS3257/seminar-on-corporate-finance), [TCE5510](https://nusmods.com/courses/TCE5510/advanced-structural-concrete-design)). When such a class is selected, the optimiser does not know how to assign it:

Image

### To Reproduce

1. Add YSS3257 to your timetable
2. Run the optimiser

### Expected behavior

Support up to 2100.

### LINKED ISSUE #4070: Optimiser does not work for mods with XX:30 times
### Describe the bug

Image

Image

### To Reproduce

1. Add YSS4281 to your timetable
2. Run the optimiser

### Expected behavior

Should support XX:30 times.

### LINKED ISSUE #4073: Optimiser: Info icon renders too small in mobile devices
### Describe the bug

Info icon is too small 

### To Reproduce

1. Go to nusmods.com/optimiser on mobile device

### Expected behavior

Should be bigger and positioned correctly

### Screenshots

Image

### PR DESCRIPTION
**Pull request by thejus03**
## Context

Closes #4069
Closes #4070
Closes #4073

## Other changes
- Added support for lessons on "Saturday" and shows "Saturday" button in frontend if there are any lessons in timetable on a Saturday
image
image

- Changed UI of timings to also now support 30 min intervals
- Changed wordings for clarity

### CODE REVIEW

File: website/api/optimiser/_models/models.go [hunk 1]
```diff
@@ -20,8 +20,8 @@ type OptimiserRequest struct {
 
 type TimetableState struct {
 	Assignments   map[string]string // lessonKey -> chosen classNo
-	DaySlots      [5][]ModuleSlot   // For each weekday, a time-sorted slice of slots
-	DayDistance   [5]float64        // Squared travel distance per day
+	DaySlots      [6][]ModuleSlot   // For each weekday (Mon-Sat), a time-sorted slice of slots
```
Comment (ravern) [inline website/api/optimiser/_models/models.go]:
```suggestion
	DaySlots      [6][]ModuleSlot   // For each day, a time-sorted slice of slots
```

File: website/src/views/optimiser/OptimiserForm.tsx [hunk 2]
```diff
@@ -171,7 +190,7 @@ const OptimiserForm: React.FC<OptimiserFormProps> = ({
             </div>
           ))}
           <div className={styles.conflictFooter}>
-            Consider marking these lessons as non-physical or choosing different free days.
+            Consider disabling live attendance for these lessons or selecting different free days.
```
Comment (ravern) [inline website/src/views/optimiser/OptimiserForm.tsx:193]: Nice!

File: website/src/views/optimiser/OptimiserResults.tsx [hunk 3]
```diff
@@ -10,17 +10,30 @@ interface OptimiserResultsProps {
   openOptimisedTimetable: () => void;
 }
 
+const scrollToBottom = () => {
+  const element = document.getElementById('optimiser-results');
+  if (element) {
+    element.scrollIntoView({ behavior: 'smooth' });
+  }
+};
```
Comment (ravern) [inline website/src/views/optimiser/OptimiserResults.tsx]: Can we use a React ref here instead of just `getElementById`?

**Review by ravern — CHANGES_REQUESTED** [review]

File: website/src/views/optimiser/OptimiserResults.tsx (hunk 3 above)
Comment (thejus03) [reply website/src/views/optimiser/OptimiserResults.tsx]: yep sure

**Review by ravern — APPROVED** [review]
LGTM
