### PR TITLE
Fixes #212

### LINKED ISSUE #212: Navbar icons for external links remain highlighted after links are visited.
An example would be the NUSWhispers icon after a user visits the page. 
screen shot 2015-05-21 at 12 27 14 am

To reproduce:

1. Click on the NUSWhispers icon in navbar
2. Upon returning to NUSMods, the icon remains highlighted

### PR DESCRIPTION
**Pull request by chunqi**
There is discrepancy between the handling of link navigation between
Chrome and the other browsers such as Safari in that focus on the anchor
is not removed.

This forces the anchor to lose focus after clicking.

### CODE REVIEW

**Comment by chunqi** [comment]
@xbili oops a tab

**Comment by xbili** [comment]
@chunqi Thanks! This is great :+1:

File: app/scripts/common/views/AppView.js [hunk 1]
```diff
@@ -20,7 +20,8 @@ module.exports = Backbone.View.extend({
   el: 'body',
 
   events: {
-    'click a[href]:not([data-bypass])': 'hijackLinks'
+    'click a[href]:not([data-bypass])': 'hijackLinks',
+    'mouseup a[href]:not([data-bypass])' : 'removeFocus',
```
Comment (yangshun) [inline app/scripts/common/views/AppView.js]: ugh trailing comma. we should run jshint before push in future :joy:

Comment (xbili) [inline app/scripts/common/views/AppView.js]: Oops my bad! Didn't catch this.

Comment (yangshun) [inline app/scripts/common/views/AppView.js]: No it's ok, small thing haha. Not critical. We'll do jshint cleanup once in a while ba.
