### PR TITLE
Scraper: Ignore lessons with no start/end time

### LINKED ISSUE #2379: Scraper: Error: Cannot read property 'replace' of null
Scraper has been crashing since Dec 17 as a 1800hrs lesson of DSA4262 has no `end_time`. Scraper should detect falsy `start_time` and `end_time`, log an error, and ignore the lesson instead.

Sentry Issue: [SCRAPER-V2-T](https://sentry.io/organizations/nusmods/issues/1393230630/?referrer=github_integration)

```
Error: Cannot read property 'replace' of null
  File "/home/ubuntu/nusmods/scrapers/nus-v2/node_modules/oboe/dist/oboe-node.js", line 2325, in Timeout._onTimeout
    throw new Error(e.message);
  File "timers.js", line 436, in ontimeout
  File "timers.js", line 300, in tryOnTimeout
  File "timers.js", line 263, in listOnTimeout
  File "timers.js", line 223, in Timer.processTimers

Error: Cannot read property 'replace' of null
```

### PR DESCRIPTION
**Pull request by taneliang**
Resolves #2379.

Modifies scraper to ignore lessons without start/end times. The affected lessons' module codes are logged to Sentry; see [example](https://sentry.io/organizations/nusmods/issues/1404161671/events/3c0a95501acf4d56a034ac1c09a13e78) (internal only).

This branch is currently checked out on our scraper prod server.

### TODO after merging

On scraper prod server:
- `git checkout master`
- `git pull`
- `git branch -D dammit-neverending-lesson`

### CODE REVIEW

File: scrapers/nus-v2/src/tasks/GetSemesterTimetable.ts [hunk 1]
```diff
@@ -198,7 +210,10 @@ export default class GetSemesterTimetable extends BaseTask implements Task<Input
       if (rawLesson) {
         rawLesson.weeks.push(lesson.eventdate);
       } else {
-        timetable[key] = mapTimetableLesson(lesson, this.logger);
+        const lessons = mapTimetableLesson(lesson, this.logger);
```
Comment (taneliang) [inline scrapers/nus-v2/src/tasks/GetSemesterTimetable.ts]: Actually... this shouldn't have been plural since it's still one lesson. Oops
